[package]
name = "casclib"
version = "0.2.1"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
casclib-sys = { path = "../casclib-sys" }
log = "0.4"

[target.'cfg(windows)'.dependencies]
widestring = "1.0"
